name: Build Firmware
on: push
# on: 
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Arduino CLI and add to PATH
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH

      - name: Set up Arduino Core
        run: |
          arduino-cli config set board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core install esp32:esp32

      - name: Install libraries
        run: |
          arduino-cli lib install "WiFiManager" || true
          arduino-cli lib install "ArduinoOTA" || true
          arduino-cli lib install "ArduinoJson" || true
          arduino-cli lib install "WebSockets" || true
          arduino-cli lib install "TCA9555" || true
          arduino-cli lib install "Adafruit GFX Library"
          arduino-cli lib install "Adafruit SSD1306"

      - name: Compile Sketch
        run: make build BOARD=esp32:esp32:esp32c3