name: Build for ESP32-C3

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Arduino CLI and add to PATH
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH

      - name: Set up Arduino Core
        run: |
          arduino-cli config set board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core install esp32:esp32

      - name: Install libraries
        run: arduino-cli lib install "WiFiManager" "ArduinoOTA" "ArduinoJson" "WebSockets" "TCA9555" || true

      - name: Compile Sketch
        run: make build BOARD=esp32:esp32:esp32c3